name: HypixelCore
version: 1.0
author: ItsKazos
main: me.itskazos.hypixelcore.Main
description: Remake of the core of hypixel

commands:
    achat:
        description: Speaks in public chat
    admin:
        description: Admin only
    badname:
        description: Bans a player for a bad name
    boop:
        description: Boop!
    disablepunch:
        description: Disables staff punch
    discord:
        description: Links to servers discord
    help:
        description: Help
    hi:
        description: Hi!
    kaboom:
        description: Kaboom
    maskrank:
        description: Masks your rank
    msg:
        description: Message a player
    nick:
        description: Nicks the player
    nuke:
        description: Nuke...
    opme:
        description: You have OP!
    rank:
        description: Set rank of a player
    shutup:
        description: Mutes chat
    spawnmob:
        description: Summons a mob
    speed:
        description: ZOOOOOOOM!
    staffchat:
        description: Staff chat
    sudo:
        description: Forces a player to execute a command
    tp:
        description: Teleport to a player
    tpall:
        description: Teleport all players to you
    tphere:
        description: Teleports a player to you
    vanish:
        description: Vanishes from existance
    wdr:
        description: Watchdog report